server:
  port: 8082

spring:
  application:
    name: Annonce-service

  datasource:
    url: jdbc:postgresql://localhost:5432/skaneasy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
