server:
  port: 8080

spring:
  application:
    name: Gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: annonce-service
          uri: lb://ANNONCE-SERVICE
          predicates:
            - Path=/annonce-service/**
          filters:
            - StripPrefix=1

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation-service/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
