server:
  port: 8083

spring:
  application:
    name: Reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/skaneasy
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
